version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jef
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - "27017:27017"

  logstash:
    build: logstash/.
    container_name: logstash
    restart: unless-stopped
    environment:
      - "LS_JAVA_OPTS=-Xms4g -Xmx4g"
    depends_on:
      - mongodb 
      - es01
      - es02
      - es03
    ports:
      - "1514:1514/udp"
    volumes:
      - $PWD/logstash/logstash-pipeline.conf:/usr/share/logstash/pipeline/logstash.conf
      - $PWD/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: es01
    restart: unless-stopped
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9201:9200

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: es02
    restart: unless-stopped
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9202:9200

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: es03
    restart: unless-stopped
    environment:
      - node.name=es03
      - discovery.seed_hosts=es02,es01
      - cluster.initial_master_nodes=es01,es02,es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9203:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana
    restart: unless-stopped
    depends_on:
      - es01
      - es02
      - es03
    environment:
      - ELASTICSEARCH_URL=http://10.7.12.107
    ports:
      - 5601:5601
    volumes:
      - $PWD/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

