version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jef
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - "27017:27017"

  logstash:
    build: logstash/.
    container_name: logstash
    restart: unless-stopped
    environment:
      - "LS_JAVA_OPTS=-Xms4g -Xmx4g"
    depends_on:
      - mongodb 
      - es1
      - es2
      - es3
    ports:
      - "1514:1514/udp"
    volumes:
      - $PWD/logstash/logstash-pipeline.conf:/usr/share/logstash/pipeline/logstash.conf
      - $PWD/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml

  es1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: es1
    restart: unless-stopped
    environment:
      - node.name=es1
      - discovery.seed_hosts=es2,es3
      - cluster.initial_master_nodes=es1,es2,es3
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - xpack.security.enabled=true
      - "ELASTIC_PASSWORD=elkP@ssw0rd"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es1:/usr/share/elasticsearch/data
    ports:
      - 9201:9200

  es2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: es2
    restart: unless-stopped
    environment:
      - node.name=es2
      - discovery.seed_hosts=es1,es3
      - cluster.initial_master_nodes=es1,es2,es3
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - xpack.security.enabled=true
      - "ELASTIC_PASSWORD=elkP@ssw0rd"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es2:/usr/share/elasticsearch/data
    ports:
      - 9202:9200

  es3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: es3
    restart: unless-stopped
    environment:
      - node.name=es3
      - discovery.seed_hosts=es2,es1
      - cluster.initial_master_nodes=es1,es2,es3
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - xpack.security.enabled=true
      - "ELASTIC_PASSWORD=elkP@ssw0rd"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es3:/usr/share/elasticsearch/data
    ports:
      - 9203:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana
    restart: unless-stopped
    depends_on:
      - es1
      - es2
      - es3
    ports:
      - 5601:5601
    volumes:
      - $PWD/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

volumes:
  es1:
  es2:
  es3:
