version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jef
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - "27017:27017"

  logstash:
    build: logstash/.
    container_name: logstash
    restart: always
    depends_on:
      - mongodb 
      - elasticsearch
    ports:
      - "514:1514/udp"
    volumes:
      - ~/git/elasticsearch/logstash/logstash-pipeline.conf:/usr/share/logstash/pipeline/logstash.conf
      - ~/git/elasticsearch/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    restart: always
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=elasticpw
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://10.5.1.114:9200
      - ELASTICSEARCH_PASSWORD=elasticpw
    ports:
      - 5601:5601

